
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookify-client
spec:
  selector:
    matchLabels:
      app: bookify-client
  replicas: 2
  template:
    metadata:
      labels:
        app: bookify-client
    namespace: bookify
    spec:
      containers:
      - name: bookify-client
        image: nayem9b/bookify-client-github-build:latest
        # volumeMounts:
        #   - name: config-volume
        #     mountPath: /opt/config
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bookify-config
              key: NODE_ENV
        - name: PORT 
          valueFrom:
            configMapKeyRef:
              name: bookify-config
              key: PORT
        - name: JWT_ACCESS_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: bookify-config
              key: JWT_ACCESS_EXPIRES_IN
        - name: JWT_REFRESH_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: bookify-config
              key: JWT_REFRESH_EXPIRES_IN
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: DATABASE_URL
        - name: BCRYPT_SALT_ROUNDS
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: BCRYPT_SALT_ROUNDS
        - name: ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: ACCESS_SECRET 
        - name: REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: REFRESH_SECRET 
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: CLERK_SECRET_KEY 
        - name:  CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key:  CLERK_PUBLISHABLE_KEY 
        - name: CLERK_API_VERSION
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: CLERK_API_URL
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: WEBHOOK_SECRET
        - name: AWS_ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: AWS_ACCESS_ID 
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: AWS_ACCESS_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: REDIS_URL    
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: JWT_SECRET    
        - name: SSL_BASE_PAYMENT_URL
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: SSL_BASE_PAYMENT_URL   
        - name: STORE_ID
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: STORE_ID    
        - name: SSL_BASE_VALIDATION_URL
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: SSL_BASE_VALIDATION_URL       
        - name: STORE_PASS
          valueFrom:
            secretKeyRef:
              name: bookify-secret
              key: STORE_PASS    
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        ports:
        - containerPort: 3000
        - containerPort: 4000
      # volumes:
      # - name: config-volume
      #   configMap:
      #     name: bookify-config
