apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookify-server-monitor
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
    app: bookify-server
spec:
  selector:
    matchLabels:
      app: bookify-server
  endpoints:
    - port: http-5000
      path: /metrics
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - dev
