apiVersion: v1
kind: Secret
metadata:
  name: bookify-backend-secret
  namespace: bookify
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9uYXllbTp0cmFwcXVlZW43QGNsdXN0ZXIwLmRhZm1yazIubW9uZ29kYi5uZXQvQm9va2lmeT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  DB_USER: bmF5ZW0=
  DB_PASSWORD: U3F2SDBOTmFRV1JYZUVKbA==
  JWT_SECRET: MGQ5NWIzMTc5Yzk5MjRhMjk2ZjYzY2I1NTI3Y2NkYzkxOWIyYThkNTQ1MzU3MGMzMjcxMjZmNWE2M2VkNmY2NWMzOTlhODljOTZkZmFhNGEzOTc0YzE0NDYzYTMyZjZiYTJmZDNiMTVjYmI4YTg4MjUyYTQ3NmZiY2Q3YzYyYjM=
  REDIS_URL: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==